<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'AbstractSvtLinter' => 'linters/AbstractSvtLinter.php',
    'GeneralSvtLinter' => 'linters/GeneralSvtLinter.php',
    'PhpLintSvtLinter' => 'linters/PhpLintSvtLinter.php',
    'SvtLintEngine' => 'engine/SvtLintEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'AbstractSvtLinter' => 'ArcanistLinter',
    'GeneralSvtLinter' => 'AbstractSvtLinter',
    'PhpLintSvtLinter' => 'AbstractSvtLinter',
    'SvtLintEngine' => 'ArcanistLintEngine',
  ),
));
