<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'SvtLintEngine' => 'engine/SvtLintEngine.php',
    'SvtPhpLintLinter' => 'linters/SvtPhpLintLinter.php',
    'SvtTextLinter' => 'linters/SvtTextLinter.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'SvtLintEngine' => 'ArcanistLintEngine',
    'SvtPhpLintLinter' => 'ArcanistLinter',
    'SvtTextLinter' => 'ArcanistLinter',
  ),
));
