#!/bin/bash
# Vytvor subor obsahujuci informacie o verzii fajru zo svn

BASE="`dirname $0`/.."
cd $BASE
VERSIONFILE="$BASE/version_info.php"

TIMESTAMP="`date +%s`"
DATE="`date '+%Y-%m-%d %H:%M:%S %Z'`"
SVNVERSION="`svnversion`"
REPOS_URL=`svn info | grep URL | sed 's/URL: //'`

function append() {
	echo "$1" >>$VERSIONFILE
}

function property() {
	append "  '$1'=>'$2',"
  echo "$1: $2"
}

echo "<?php" >$VERSIONFILE
append "// This file was automatically generated by scripts/make_version.sh"
append "// Do not modify it. Run scripts/make_version.sh instead"
append "return array("

property url "$REPOS_URL"
property timestamp "$TIMESTAMP"
property date "$DATE"
property revision "svn$SVNVERSION"

append ");"
